### ISSUE TITLE
Won't Get Variables from LiveProfessor Remotely

### ISSUE THREAD

**Issue by mikecreates86** [bitfocus/companion-module-audiostrom-liveprofessor#9]
On the latest version of LiveProfessor and stable Companion, with Companion running on a separate machine, I am unable to pull in dynamic information from LiveProfessor. In other words, I can send commands for example to trigger snapshots but not see the dynamic name of the snapshots in Companion. Something is broken or blocked and I can't figure it out. When using a local instance of Companion on the same machine as LiveProfessor, it works.

**Comment by mikecreates86** [comment]
Any word on this? I narrowed this to an issue where Companion is not saving the IP change from 127.0.0.1. Very clear from the logs that anything on a remote machine will not work. And this used to work. Can we please get a fresh look at this with the latest Companion builds? In the beta? Something?

**Comment by jdbressler** [comment]
@haakonnessjoen @willosof @krocheck @Julusian Is anyone able to look at this?  I have the same exact issue as @mikecreates86 when trying to get feedbacks from the module when I host it on a Companion Pi.  The module does not seem to accept information coming from the Live Professor software when it is running on a different machine.  Locally hosted in 127.0.0.1 works as intended for me.

**Comment by audiostrom** [comment]
This should be fixed in the latest commit. I will close this once confirmed

**Comment by lelesound** [comment]
HI,
Is possible to add 20 rotary more ?
Thanks so much

Emanuele

**Comment by mikecreates86** [comment]
@audiostrom what is happening with this? I thought a fix was coming in the next release but 4.0 just released and nothing. Still broken on my end. How can this be fixed where variables don't work remotely?

**Comment by mikecreates86** [comment]
@audiostrom yet again asking about what happened with this update? I thought this was coming any time now but it's been since March 12 that you said this was coming in the next update. Really wanting this to be fixed.

**Comment by mikecreates86** [comment]
@audiostrom checking in AGAIN after it was commented as being fixed on the next release in March of 2025. This is such a small bug that hinders the ability to use the LiveProfessor module anywhere but locally. Please update this!

**Comment by NoFear13X** [comment]
I just downloaded LiveProfessor to test for our live performances, and quickly realized this bug in action. Is this something that will get fixed? If not, I don't see myself purchasing the software over Waves SuperRack since the only reason I'm considering LP is the Companion integration.  If there's a Beta or software or something I can download, please advise. @audiostrom

**Comment by mikecreates86** [comment]
@NoFear13X I wouldn't hold your breath. I have reported this and waited and waited and they have done nothing. Such a small simple bug but it's making me plan my exit from relying on LiveProfessor altogether.

I'd love to still be proven wrong as Companion integration is hard to find from any other plugin host. But broken integration doesn't count either.

**Comment by NoFear13X** [comment]
@mikecreates86 Well, I'm giving them 97 days to fix it, lol

**Comment by jdbressler** [comment]
@nofear13x Not certain, but it could have something to do with whoever is maintaining this integration not submitting the changes to be included in the new method of which Bitfocus is reviewing modules.  I think it’s an automated process so they don’t have to wait for every new version of Companion to be released for a module update.

**Comment by audiostrom** [comment]
@jdbressler Thanks for the heads up. The issue was solved a year ago, but the fix never got published. I have now spent some time figuring out the new release system and hope it will make it to a release.

**Comment by NoFear13X** [comment]
> [@jdbressler](https://github.com/jdbressler) Thanks for the heads up. The issue was solved a year ago, but the fix never got published. I have now spent some time figuring out the new release system and hope it will make it to a release.

That's awesome news, thank you!

**Comment by mikecreates86** [comment]
@audiostrom well? Any news on when this will be available in Companion?

**Comment by mikecreates86** [comment]
@audiostrom is there an update coming? Isn't the new Companion set to let you release this as an updated module any time and not wait for the main releases? Is it fixed in a beta?

@jdbressler Any help you can give to this?

@NoFear13X as you can see, progress on this seems to be short lived...

**Comment by jdbressler** [comment]
@mikecreates86 I have no more input on this.  I am an end user just like you.  I can only guess/hypothesize that since @audiostrom submitted the module into the new system, the automated updates won’t start until the next stable point release.  You could maybe try the beta release?

**Comment by audiostrom** [comment]
Hi
The module was submitted for approval, 3 weeks ago. Then the companion team reviewed it on Monday and left some notes and improvements in a pull request. I then merged their changes the same day and sent it to approval again, and it is currently in their todo-queue

**Comment by mikecreates86** [comment]
@audiostrom another check-in a week later. Any news?

**Comment by NoFear13X** [comment]
> [@audiostrom](https://github.com/audiostrom) another check-in a week later. Any news?

I switched to Ableton. Could have been a great software if the dev supported it and communicated. Oh well 🤷‍♂️ 

/unsubscribe 👋
